Lock-null resources + PUT Chunked
WebDav server now works with the finder
Still issues with MSOffice 2016, but it might be due to some file permissions

Also, have some problems in adding relatively big files (>5mb). It is a bit slow (due to diagnostic and the way files are appened probably).

Also get this problem afterwards:
Error: uk.ac.standrews.cs.webdav.impl.RequestHandler::tryToCloseSocket : While processing request from localhost Exception: Broken pipe
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:154)
	at uk.ac.standrews.cs.webdav.impl.Response.write_unchunked(Response.java:251)
	at uk.ac.standrews.cs.webdav.impl.Response.close(Response.java:216)
	at uk.ac.standrews.cs.webdav.impl.methods.GET.execute(GET.java:61)
	at uk.ac.standrews.cs.webdav.impl.RequestHandler.runRequest(RequestHandler.java:86)
	at uk.ac.standrews.cs.webdav.impl.RequestHandler.run(RequestHandler.java:40)
	at uk.ac.standrews.cs.webdav.entrypoints.WebDAVServer$1.performAction(WebDAVServer.java:64)
	at uk.ac.standrews.cs.util.ActionQueue$1.run(ActionQueue.java:203)